baseURL = 'https://nanoporeflanders.be'
languageCode = 'en-us'
title = 'Flanders Nanopore Day'
theme = 'flanders-nanopore'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'The Flanders Nanopore Day - April 17th, 2026'
  author = 'Flanders Nanopore Day Organizing Committee'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Practical'
    url = '/practical/'
    weight = 2
  [[menu.main]]
    name = 'Registration'
    url = '/registration/'
    weight = 3
  [[menu.main]]
    name = 'Abstracts'
    url = '/abstracts/'
    weight = 4
  [[menu.main]]
    name = 'Project prizes'
    url = '/projects/'
    weight = 5
  [[menu.main]]
    name = 'Program'
    url = '/program/'
    weight = 6
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 7
